#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["AutoscalerApi/AutoscalerApi.csproj", "AutoscalerApi/"]
RUN dotnet restore "AutoscalerApi/AutoscalerApi.csproj"
COPY . .
WORKDIR "/src/AutoscalerApi"
RUN dotnet build "AutoscalerApi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "AutoscalerApi.csproj" -c Release -o /app/publish

FROM base AS final

RUN dotnet tool install --global dotnet-trace
RUN dotnet tool install --global dotnet-dump
RUN dotnet tool install --global dotnet-counters
RUN echo "export PATH="\""$PATH:/root/.dotnet/tools"\"" >> ~/.bash_profile

WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "AutoscalerApi.dll"]